### ISSUE TITLE
Time format?

### ISSUE THREAD

**Issue by ijo-amali** [wuweijian1997/FlutterCountdownTimer#1]
Nowhere in the documentation does it say the format of the time you must input for the `endTime` parameter of the `CountdownTimer` function. What exactly is it?

**Comment by wuweijian1997** [comment]
time stamp.
```
final int endTime;
```
> js
```
new Date().getTime()
```
> dart
```
new DateTime.now().millisecondsSinceEpoch;
```
> Java
```
new Date().getTime();
```

**Comment by ijo-amali** [comment]
oh got it, thank you!
