### ISSUE TITLE
Stop before the end

### ISSUE THREAD

**Issue by redDwarf03** [wuweijian1997/FlutterCountdownTimer#12]
Hello
thank for you widget ! very usefull
i have a question:

I add a countdown timer with an event at the endtime.
But sometimes, if the user do some actions, I want to stop before the end, my countdown timer.
How it is possible ?

For example, I would like stop the count before the end sometimes... actually, if I go to the page2 or other thing, onEnd method execute always at 0 the push..

 CountdownTimer(
          endTime: endTime,
          onEnd: () {
              Navigator.push<dynamic>(
                  context,
                  MaterialPageRoute<dynamic>(
                    builder: (BuildContext context) => GoToPage2(),
                  ));
            }
           )

thx

**Comment by wuweijian1997** [comment]
Will destroying the CountdownTimer solve the problem?
```
bool _isEnd = false;
...
if(_isEnd) 
  Text('isEnd');
else
  CountdownTimer(
    endTime: endTime,
    onEnd: () {
      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (BuildContext context) => GoToPage2(),
        ));
     }
)
```

**Comment by redDwarf03** [comment]
thx!
