### ISSUE TITLE
please there is no docs for this how can people use your package without docs

### ISSUE THREAD

**Issue by yassinedevop** [wuweijian1997/FlutterCountdownTimer#21]
I have spend a lot of hours trying to understand what your wrote there . please add a docs to this project so people can uderstand what you had written

**Comment by wuweijian1997** [comment]
Hello, I added some comments, hope to help you. You are also welcome to submit pr.thx.

**Comment by yassinedevop** [comment]
Okay i will check them, Thanks a lot for the effort given to this project
