### ISSUE TITLE
Counting Issue

### ISSUE THREAD

**Issue by arjunbhandari3** [wuweijian1997/FlutterCountdownTimer#25]
While counting down the remaining time, the numbers '24'  on hours and  '60' on minutes which should be both '00' are provided null.

**Comment by wuweijian1997** [comment]
Can you give me a demo?

**Comment by arjunbhandari3** [comment]
![demo](https://user-images.githubusercontent.com/33949575/108628531-98eae200-7483-11eb-97cc-6d9c07361b60.jpg)
This occurs in case of hours and minutes.

**Comment by wuweijian1997** [comment]
Thank you for your feedback,I have released version 3.0.1 to solve this problem.

You can use it, too `time.hours  ?? '00'` solves this problem temporarily.
