### ISSUE TITLE
Text Alignment

### ISSUE THREAD

**Issue by congfandi** [wuweijian1997/FlutterCountdownTimer#3]
Please add text alignment.. thanks

**Comment by AliAnilKocak** [comment]
Check this pr

https://github.com/wuweijian1997/FlutterCountdownTimer/pull/2

**Comment by congfandi** [comment]
hi @AliAnilKocak , this is not about position actually,, the text is going bigger as width layout, event you just showing time its will make the text bigger.

**Comment by congfandi** [comment]
@AliAnilKocak  i try using ure PR and its work for me.. now my countdown timer its going to middle .. thanks .. i'll close the issue.
