### ISSUE TITLE
Display format when show 1 digit

### ISSUE THREAD

**Issue by saputraiqbal** [wuweijian1997/FlutterCountdownTimer#36]
Hi, before I ask something, I want to say thanks for your package. It helps me.

Currently, I want to show a countdown timer in format like [hours:minutes:seconds]. But unfortunately, when one of them remaining 1 digit, it shows 1 digit, like [1:1:10]. I wonder if I can change the countdown display to become like [01:01:10]. Or, is something I missing when I writing the codes?

Here is the sample code I write to achive my goal.

```
...
CountdownTimer(
    endTime: DateTime.now().millisecondsSinceEpoch + 1000 * 30,
    widgetBuilder: (_, timeRemain){
      if (timeRemain == null) {
        return Text("00:00:00");  
      } else {
        return Text('${timeRemain.hours ?? 0}:${timeRemain.min ?? 00}:${timeRemain.sec}');
      }
    },
)
...
```

Thanks in advance

**Comment by wuweijian1997** [comment]
That will do it.
```
  String format(int num) {
    if(num < 10) {
      return '0$num';
    }
    return num.toString();
  }

...

${format(time.sec ?? 0)}
```

**Comment by saputraiqbal** [comment]
Thanks! Works like charm 😍👍
