### ISSUE TITLE
没用了

### ISSUE THREAD

**Issue by wangxingxing123654** [wuweijian1997/FlutterCountdownTimer#4]
放进去都没有东西显示出来了】

**Comment by wuweijian1997** [comment]
应该是时间戳过期了,你要选一个当前时间之后的时间戳.

js获取一小时之后的时间戳
`
Date.now() + 1000 * 60 *60
`

dart 获取一小时之后的时间戳
`
DateTime.now().millisecondsSinceEpoch + 1000 * 60 * 60;
`

如果设置的时间戳是已过期的时间戳,那么它是不会显示的.

**Comment by wuweijian1997** [comment]
已更新,可以看一下新版本.
