### ISSUE TITLE
how to cancel timer on page change?

### ISSUE THREAD

**Issue by harshraj21** [wuweijian1997/FlutterCountdownTimer#43]
it always gives me error saying set state was called from widget which was not visible in the widget tree..

How to fix this and dispose the timer properly on page change (route to another page)
without clicking any button

**Comment by wuweijian1997** [comment]
```
CountdownTimerController.dispose()
```

**Comment by harshraj21** [comment]
> ```
> CountdownTimerController.dispose()
> ```

when i try this it tells me `This method should only be called by the object's owner.`

**Comment by wuweijian1997** [comment]
You can refer to this.You need to instantiate CountdownTimerController first .
```
class _CountdownTimerPageState extends State<CountdownTimerPage>
    with SingleTickerProviderStateMixin {
  late CountdownTimerController controller;
  int endTime = DateTime.now().millisecondsSinceEpoch +
      Duration(seconds: 30).inMilliseconds;

  @override
  void initState() {
    super.initState();
    controller =
        CountdownTimerController(endTime: endTime, onEnd: onEnd, vsync: this);
  }

  void onEnd() {
    print('onEnd');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CountdownTimer(
        controller: controller,
      ),
    );
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }
}
```

**Comment by harshraj21** [comment]
i have tried your code and modified it a bit to work in my case now on disposing it i am getting the following errors

**********************************************************************************************************************************************
════════ Exception caught by widgets library ════════════════════════
The following assertion was thrown while finalizing the widget tree:
_CustomTimeKeeperState#b7f6c(tickers: tracking 12 tickers) was disposed with an active Ticker.

_CustomTimeKeeperState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. All Tickers must be disposed before calling super.dispose().

Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.

The offending ticker was: _WidgetTicker(created by _CustomTimeKeeperState#b7f6c(tickers: tracking 1 ticker))
**********************************************************************************************************************************************

**Comment by harshraj21** [comment]
how to dispose the ticker which was generated from the mixin?

**Comment by wuweijian1997** [comment]
Can you provide the code for the minimum run? I can find out what the problem is if I have the code.

**Comment by wuweijian1997** [comment]
Maybe this will be enough for you. ` controller.disposeTimer();`,Don't ` with SingleTickerProviderStateMixin `
```
class _CountdownTimerPageState extends State<CountdownTimerPage> {
  late CountdownTimerController controller;
  int endTime = DateTime.now().millisecondsSinceEpoch +
      Duration(seconds: 30).inMilliseconds;

  @override
  void initState() {
    super.initState();
    controller = CountdownTimerController(endTime: endTime, onEnd: onEnd);
  }

  void onEnd() {
    print('onEnd');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CountdownTimer(
        controller: controller,
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.stop),
        onPressed: () {
          controller.disposeTimer();
        },
      ),
    );
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }
}

```

**Comment by harshraj21** [comment]
Minimum run

```
class _CustomTimeKeeperState extends State<CustomTimeKeeper> {
  late CountdownTimerController controller;
  late Map ret;
  bool _isInit = false;
  @override
  void initState() {
    ret = RecordedProvider.heavycalc(
      widget.schedule,
      widget.expire,
    );
    controller = CountdownTimerController(
      endTime: ret['time'],
      onEnd: () {
        Provider.of<RecordedProvider>(context, listen: false).getData();
      },
    );
    _isInit = true;
    super.initState();
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }
```

**Comment by harshraj21** [comment]
the action button cancel timer works but in my application i cant have a button for that.. as imagine it as a premier of something is going to happen and countdown for that is to be displayed so i cant rely on press of a button to cancel the timer,,

And to be clear about my requirements:  while timer is running if i navigate to another page i have to cancel / dispose the timer and free its allocated resources else memory leak is happening

BTW: huge thanks to you as you are helping me fix this error appreciate your assistance
